### ISSUE TITLE
Date Object Incompatibility with json-schema-to-ts Type Generation

### ISSUE THREAD

**Issue by mmdalix** [fastify/fastify-type-provider-json-schema-to-ts#106]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Plugin version

4.0.0

### Node.js version

20.11.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

24.1.0

### Description

When working with fastify and its response serializer (fast-json-stringify), I noticed an inconsistency with how date objects are handled between fast-json-stringify and json-schema-to-ts.

The fast-json-stringify serializer allows me to directly provide a Date object, which is then correctly serialized to a date-time string format in the response. However, json-schema-to-ts requires the type definition to explicitly expect a string, not a Date, even though the JSON schema specifies a date-time format.

Example Schema:
`response: {
    200: {
        type: 'object',
        properties: {
            createdAt: { type: 'string', format: "date-time" },
        }
    }
}
`

### Expected Behavior

It would be helpful if json-schema-to-ts could accommodate Date objects when a JSON schema property is set to a date-time format, matching the behavior of fast-json-stringify.

**Comment by mcollina** [comment]
I do not have an idea on how this could be achieved, but a PR that implemented this would be amazing.

**Comment by bcomnes** [comment]
I think I added support for a fix/workaround in this PR: https://github.com/fastify/fastify-type-provider-json-schema-to-ts/pull/103

Using the deserialize type option on the serializer lets you return Date objects.

**Comment by mikaelkaron** [comment]
Wow @bcomnes - really firing on all cylinders today, this is the second issue I had with this plugin that you are fixing today.
