### ISSUE TITLE
Uable to use shema inheritence

### ISSUE THREAD

**Issue by mikaelkaron** [fastify/fastify-type-provider-json-schema-to-ts#113]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.2

### Plugin version

4.0.1

### Node.js version

22.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

debian 12

### Description

When trying to follow this [guide on schema inheritance](https://json-schema.org/blog/posts/modelling-inheritance) I'm only able to see the properties from the parent schema, not the child one.

### Expected Behavior

Schema inheritance to work as expected

**Comment by bcomnes** [comment]
Please post an example of what isn't working. Various forms of inheritance do work.

**Comment by mikaelkaron** [comment]
Looks like you were entirely correct, the error is not in this plugin, or perhaps not at the server-side at all...

I created a [reproducer repo](https://github.com/mikaelkaron/fastify-json-schema-inherit-error) where you can see:

- ✅  schemas are correctly enforced
- ✅ `swagger-ui` picks up the two models
- 🟥  models are _not_ correctly represented in `swagger-ui`

I'm not sure if the generated schema is correct (server side) or just not displayed correctly (client side)

Since the original project is a [platformatic](https://platformatic.dev) project and they use [scalar](https://scalar.com) I've tried it there as well with the same error.
