### ISSUE TITLE
TypeScript only evaluating to `any` when using @fastify/type-provider-json-schema-to-ts

### ISSUE THREAD

**Issue by rmehner** [fastify/fastify-type-provider-json-schema-to-ts#12]
Hi there,

migrating to fastify v4 I was very excited for better TS support on JSON schemas. So I went ahead and tried the example provided on the docs site: https://www.fastify.io/docs/latest/Reference/Type-Providers/#json-schema-to-ts

However, if I do that, `foo` and `bar` will always be of type `any`. Am I holding it wrong? I was expecting the types to be `number` and `string` respectively.

```ts
import { JsonSchemaToTsProvider } from '@fastify/type-provider-json-schema-to-ts'

import fastify from 'fastify'

const server = fastify().withTypeProvider<JsonSchemaToTsProvider>()

server.get(
  '/route',
  {
    schema: {
      querystring: {
        type: 'object',
        properties: {
          foo: { type: 'number' },
          bar: { type: 'string' },
        },
        required: ['foo', 'bar'],
      },
    } as const
  },
  request => {
    const { bar } = request.query
    bar.push('foo') // I'd expect this to fail with `error TS2339: Property 'push' does not exist on type string`
  }
)
```

Thank you for your help already!

## Your Environment

- *node version*: 18
- *fastify version*: >=4.0.0
- *typescript version*: 4.7.4

**Comment by sinclairzx81** [comment]
@RafaelGSS Just tested this on the TypeScript playground and the type resolution appears to be working ok (TS 4.7.4)

[TypeScript Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgKQM4QHYGUDGALAUxAEMAVCU1ABSggDdgATAqOAXzgDNaQ4ByAAKdiqGME4BPAPQwJYAgFowtBsygKAVugwLU+IsQUwIR1HwCwAKCuhIsLiLGSuPfsNHiJF65ZyZRcKgsdCxwALwOHpIAFACUAHQA7sAweKRyBDT0TCwAPGiYuIQk5JRZqiwAfHFWVkFQIVDxAOYEMNFWcPxStACuMAR8ADSdiKNdesXEAFxjll0LcACOvSwSolDAGM2zCOOLcLLys3wQAEYaBDgww-uLyhDysMAEqLt3B5wQELuHGScYXogM4sPjsEbzA6LM7EKC-I4EE4bLbNMFsCFQrroj5dKAEFbAPGMWYAbT4Xwgw34MKgfAAuhiDtjIVi4CI4H4MKJRszcfjVgEwpU5otOQEkDT2OE4HiVq8YPE5VAJPsafEwL1UHhouTvnxYnApFI4ABJPiMOAEAAe8muhzwwFQhwgDmAABs4MlUnAAAYsWisUhYABMAGZQwBOWZZJ6yfgarVgxgQV5wDAQeDWx3wTB-eSBGCbbY+nlWWJAA)

@rmehner  Just have a quick check that your `tsconfig.json` file s configured for `strict: true`.

**Comment by alphaone** [comment]
Hey, I am getting the same error as @rmehner . I can see how the linked playground example works, but when I copy the code into my project, it stops to infer the type from the schema.

Even if I use the example from the ReadMe I get type `unknown` :\
```
const plugin: FastifyPluginAsyncJsonSchemaToTs = async (fastify, _opts) => {
  fastify.get(
    '/',
    {
      schema: {
        body: {
          type: 'object',
          properties: {
            x: { type: 'string' },
            y: { type: 'number' },
            z: { type: 'boolean' },
          },
          required: ['x', 'y', 'z'],
        } as const,
      },
    },
    (req) => {
      /// Property 'x' does not exist on type 'unknown'.ts(2339)
      const { x, y, z } = req.body
    },
  )
}
```

I am using:
- "node": "18.11.0"
- "typescript": "4.8.4"
- "@fastify/type-provider-json-schema-to-ts": "2.1.1"
- "fastify": "4.9.2"
- "json-schema-to-ts": "2.5.5" (as a dev dependency)

**Comment by alphaone** [comment]
Just for later reference, I found my problem. I had a wrong setting in my `tsconfig.json` (`"noStrictGenericChecks": true,`) that made the `json-schema-to-ts` to compute useless types.

Removing the setting lets the type inferring from json-schema work like a charm 👌
