### ISSUE TITLE
Build wasn't ran before the last release of 2.2.0

### ISSUE THREAD

**Issue by kalvenschraut** [fastify/fastify-type-provider-json-schema-to-ts#27]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.x

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

using custom gentoo

### Description

Updated to latest version than saw TS error complaining about no generic, but there is one in the root/index..ts.  I then realized root/dist/index.d.ts doesn't have the generic I added to root/index.ts.

Can look at adding a prepublish script to force build to be ran before every publish.

### Steps to Reproduce

install as a package in another repo, then can see the index.d.ts in dist that the package.json points to does not match the index.ts file at the root of this repo.

**Comment by Uzlopak** [comment]
@RafaelGSS

**Comment by RafaelGSS** [comment]
Sorry for that. Fixed in v2.2.1.
