### ISSUE TITLE
json-schema-to-ts provider does not infer types (always unknown)

### ISSUE THREAD

**Issue by sbeben** [fastify/fastify-type-provider-json-schema-to-ts#40]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.11.0

### Plugin version

^2.2.2

### Node.js version

18.12.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

There is the same thread already exists on [stackoverflow](https://stackoverflow.com/questions/73433563/fastify-json-schema-to-ts-type-provider-doesnt-work?rq=1). Types just does not get infered and remains 'unknown'.

### Steps to Reproduce

Here is the [stackblitz reproduce](https://stackblitz.com/edit/node-p2d3nq?file=package.json,index.ts) with direct copy-paste of the code from docs.

**Comment by mcollina** [comment]
Thanks for reporting! It seems we are currently slammed and did not have time to look into this.

Maybe @fastify/typescript can help?

**Comment by Explicit12** [comment]
I fixed this by installing json-schema-to-ts as peer dependence. It also works in your stackblitz.

`yarn add -P json-schema-to-ts`

**Comment by climba03003** [comment]
The problem is exactly related to the author did not install `json-schema-to-ts`.
