### ISSUE TITLE
Schemas fail to convert to types with json-schema-to-ts 2.9+

### ISSUE THREAD

**Issue by mhio** [fastify/fastify-type-provider-json-schema-to-ts#49]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

2.2.2

### Node.js version

18.16.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

With json-schema-to-ts@2.9.0 the simple example fails to infer types from the schema:
```
import { JsonSchemaToTsProvider } from '@fastify/type-provider-json-schema-to-ts'

import fastify from 'fastify'

const server = fastify().withTypeProvider<JsonSchemaToTsProvider>()

server.get(
  '/route',
  {
    schema: {
      querystring: {
        type: 'object',
        properties: {
          foo: { type: 'number' },
          bar: { type: 'string' },
        },
        required: ['foo', 'bar'],
      },
    } as const
  },
  request => {
    const { bar } = request.query
    bar.push('foo') // I'd expect this to fail with `error TS2339: Property 'push' does not exist on type string`
  }
)
```
Works (or fails) as expected with json-schema-to-ts@2.8.2 

But fails on json-schema-to-ts@2.9.0 with:
```
server.ts:22:13 - error TS2339: Property 'bar' does not exist on type 'unknown'.

22     const { bar } = request.query
               ~~~

server.ts:22:21 - error TS2589: Type instantiation is excessively deep and possibly infinite.

22     const { bar } = request.query
                       ~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/server.ts:22
```

Interestingly `json-schema-to-ts@2.9.0` looks to be an update in release process rather than functional changes, so I will raise over there as well.  

### Steps to Reproduce

in sample fastify-type-provider-json-schema-to-ts project
yarn add json-schema-to-ts@~2.8.0
tsc # expected
yarn add json-schema-to-ts@~2.9.0
tsc # no schema types

### Expected Behavior

Same as  json-schema-to-ts@2.8.2

There appears to be a [similar issue in json-schema-to-ts@2.8.0](https://github.com/ThomasAribart/json-schema-to-ts/issues/132) that was resolved, but I can't reproduce that issue in fastify-type-provider-json-schema-to-ts with json-schema-to-ts@2.8.0

**Comment by DimaNevelev** [comment]
Solved in json-schema-to-ts@2.9.1

**Comment by Uzlopak** [comment]
@Eomm 

Revert the Patch from three days ago?

**Comment by Eomm** [comment]
It was a dev dep... I'm not the right person to ask for typescript issue

**Comment by Uzlopak** [comment]
Closing. Solves in upstream

**Comment by BoscoDomingo** [comment]
Still happening for me. I opened #68
