### ISSUE TITLE
v3 released but not available on NPM

### ISSUE THREAD

**Issue by sinedied** [fastify/fastify-type-provider-json-schema-to-ts#73]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Plugin version

2.2.2

### Node.js version

18.19

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.2.1

### Description

I have the issue https://github.com/fastify/fastify-type-provider-json-schema-to-ts/issues/68 in my project, which is fixed by v3 of this package, but the latest NPM version is still 2.2.2.

### Steps to Reproduce

`npm i @fastify/type-provider-json-schema-to-ts@3`

### Expected Behavior

v3 to be published on NPM :)

**Comment by gurgunday** [comment]
cc @climba03003

**Comment by climba03003** [comment]
https://www.npmjs.com/package/@fastify/type-provider-json-schema-to-ts/v/3.0.0
